#!/bin/bash

export GO111MODULE=on

set -e

CC=${CC:-gcc}

go install -v github.com/google/wuffs/cmd/wuffs-c
export WUFFSROOT=$(go list -m -f {{.Dir}} github.com/google/wuffs)

wuffs-c gen -package_name zstd decode.wuffs consts.wuffs >decode.h

cp -f $WUFFSROOT/release/c/wuffs-unsupported-snapshot.c wuffs-base.c

$CC -x c -DWUFFS_IMPLEMENTATION wuffs-base.c wuffsmain.c -o zstd

rm -f decode.h wuffs-base.c
